import type { WorkbenchPalette } from "./model";

export function createWorkbenchCssVars(palette: WorkbenchPalette): Record<string, string> {
  return {
    "--wb-active-bg": palette.active,
    "--wb-accent": palette.accent,
    "--wb-accent-active": palette.accentActive,
    "--wb-accent-hover": palette.accentHover,
    "--wb-accent-soft": palette.accentSoft,
    "--wb-accent-softer": palette.accentSofter,
    "--wb-bg": palette.bg,
    "--wb-border": palette.border,
    "--wb-border-soft": palette.borderSoft,
    "--wb-card-bg": palette.panel,
    "--wb-card-elevated-bg": palette.panelElevated,
    "--wb-card-muted-bg": palette.panelMuted,
    "--wb-danger": palette.danger,
    "--wb-header-bg": palette.header,
    "--wb-header-border": palette.border,
    "--wb-header-edge": palette.borderSoft,
    "--wb-hover-bg": palette.hover,
    "--wb-input-bg": palette.input,
    "--wb-panel-muted-bg": palette.panelMuted,
    "--wb-nav-active-bg": palette.accentSofter,
    "--wb-nav-indicator": palette.accent,
    "--wb-sidebar-bg": palette.sidebar,
    "--wb-success": palette.success,
    "--wb-text": palette.text,
    "--wb-text-muted": palette.textMuted,
    "--wb-text-secondary": palette.textSecondary,
    "--wb-text-strong": palette.textStrong,
    "--wb-text-subtle": palette.textSubtle,
    "--wb-warning": palette.warning,
    "--wb-workbench-bg": palette.workbench,
  };
}
